// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Chiron",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Chiron",
            targets: ["AppModule"],
            bundleIdentifier: "ak.TrackPD",
            teamIdentifier: "9B9QB6W23M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .healthcareFitness
        )
    ],
    dependencies: [
        .package(url: "https://github.com/buh/Spiral.git", "1.0.1"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Spiral", package: "spiral")
            ],
            path: ".",
            resources: [
                .process("Resources"),
                .copy("MLModel/parkinson_spiral.mlmodelc"),
                .copy("MLModel/parkinson_wave.mlmodelc")
            ]
        )
    ]
)